In [1]:
import numpy as np

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [5]:
array_b = np.array([[1,2,3],
                    [4,5,6]])

In [6]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(array_a)

numpy.ndarray

In [10]:
print(array_a)

[1 2 3]


In [11]:
array_a.shape

(3,)

In [17]:
array_b.shape[1]

3

In [13]:
type(array_b)

numpy.ndarray

In [18]:
array_c = np.array(1)

In [19]:
array_c

array(1)

In [20]:
type(array_c)

numpy.ndarray

In [21]:
print(array_c)

1


In [22]:
array_c.shape

()

In [23]:
array_d = np.array([15])

In [24]:
type(array_d)

numpy.ndarray

In [25]:
print(array_d)

[15]


In [26]:
array_d.shape

(1,)

In [27]:
array_e = np.array([[15]])

In [28]:
array_e.shape

(1, 1)

In [29]:
type(array_e)

numpy.ndarray

In [30]:
print(array_e)

[[15]]


In [31]:
f = np.array([[14,13]])

In [32]:
f.shape

(1, 2)

In [33]:
print(f)

[[14 13]]


In [34]:
f = np.array([[14,13],[14,15]])

In [38]:
print(f)

[[14 13]
 [14 15]]


### Array vs Lists

In [39]:
list_a = [1,2,3,4,5,6]

In [40]:
len(list_a)

6

In [52]:
list_a = [[1,2,3],[4,5,6]]

In [57]:
list_a

[[1, 2, 3], [4, 5, 6]]

In [58]:
type(list_a)

list

In [53]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [54]:
# since its list of list
len(list_a)

2

In [75]:
array_a = np.array(list_a)

In [76]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
type(array_a)

numpy.ndarray

In [49]:
# this is a tupple
b = [1,3,3],[4,5,6]

In [50]:
len(b)

2

In [51]:
type(b)

tuple

In [60]:
array_a.shape

(2, 3)

In [62]:
list_a.shape

AttributeError: 'list' object has no attribute 'shape'

In [63]:
len(list_a)

2

In [64]:
len(array_a)

2

In [65]:
len(list_a[0])

3

In [67]:
# array operations work element wise, list operations do not

In [68]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [69]:
list_b

[1, 2, 3, 4, 5, 6]

In [70]:
array_b

array([5, 7, 9])

In [71]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
array_a[1,0]

4

In [73]:
import math
array_a = math.sqrt(array_a[1,0])

In [74]:
array_a

2.0

In [77]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])