In [1]:
import numpy as np

In [19]:
array_a = np.array([[1,2,3],[4,5,6]])

In [3]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array_a[1,1]

5

In [6]:
array_a[1,1] = 55

In [7]:
array_a

array([[ 1,  2,  3],
       [ 4, 55,  6]])

#### change entire vector

In [20]:
array_a[0] = 9

In [21]:
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [22]:
array_a[:,2] = np.array([11,11])

In [23]:
array_a

array([[ 9,  9, 11],
       [ 4,  5, 11]])

In [24]:
list_a  = [8,7,8]

In [25]:
array_a[0]

array([ 9,  9, 11])

In [26]:
array_a[0] = list_a

In [27]:
array_a

array([[ 8,  7,  8],
       [ 4,  5, 11]])

In [30]:
# here the array_a took the values from list_a and made it ndarray
type(array_a)

numpy.ndarray

In [31]:
# assigning to all values in ndarray

In [32]:
array_a[:] = 0

In [33]:
array_a

array([[0, 0, 0],
       [0, 0, 0]])